spring:
  mvc:
   static-path-pattern: /static/**
  #开始thymeleaf设置
  thymeleaf:
  #禁用模板缓存
   cache: false
  #设置文字消息
  messages:
   encoding: UTF-8
   basename: message_zh_CN
  web:
   resources:
    static-locations: classpath:/static/
  datasource:
    username: root
    password: changye
    url: jdbc:mysql://localhost:3306/web3dschool?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.zytc.web_3d_school.pojo
  configuration:
    map-underscore-to-camel-case: true